name              = Catalyst-Plugin-Session-Store-DBIC
author            = Daniel Westermann-Clark <danieltwc@cpan.org>
author            = Andrew Rodland <andrew@cleverdomain.org>
license           = Perl_5
copyright_holder  = Daniel Westermann-Clark and Andrew Rodland
copyright_year    = 2006 - 2026

;;; Gather
[Git::GatherDir]
exclude_filename = Makefile.PL
exclude_filename = META.json
exclude_filename = LICENSE
exclude_filename = README.md

[GatherFile]
filename = .perlcriticrc

;;; Metadata
[Git::Contributors]

[MetaProvides::Package]

[MetaResources]
bugtracker.web    = https://rt.cpan.org/Public/Dist/Display.html?Name=Catalyst-Plugin-Session-Store-DBIC
bugtracker.mailto = bug-Catalyst-Plugin-Session-Store-DBIC@rt.cpan.org
repository.url    = https://github.com/perl-catalyst/Catalyst-Plugin-Session-Store-DBIC.git
repository.web    = https://github.com/perl-catalyst/Catalyst-Plugin-Session-Store-DBIC
repository.type   = git

[PrereqsFile]

[UseUnsafeInc]
dot_in_INC = 0

;;; Modification
[PodWeaver]
; authordep Pod::Weaver::Section::Contributors
; authordep Pod::Weaver::Plugin::StopWords

;;; Extra Files
[License]
[MetaJSON]
[MetaYAML]
[Manifest]
[Pod2Readme]

;;; Installer
[MakeMaker]

[StaticInstall]
mode = on

;;; Tests
[MetaTests]
[MojibakeTests]
[PodSyntaxTests]
[Test::CPAN::Changes]
:version = 0.013
filename = xt/author/cpan-changes.t
[Test::ChangesHasContent]
[Test::Compile]
[Test::EOL]
[Test::Kwalitee]
filename = xt/author/kwalitee.t
[Test::MinimumVersion]
[Test::NoTabs]
[Test::Perl::Critic]
:version = 3.003
profile = .perlcriticrc
verbose = 8
[Test::Pod::Coverage::TrustMe]
[Test::PodSpelling]
[Test::Portability]
options = test_one_dot = 0
[Test::ReportPrereqs]
[Test::Version]

;;; Repo files
[CopyFilesFromRelease]
filename = Makefile.PL
filename = META.json
filename = LICENSE
[ReadmeAnyFromPod / ReadmeGFMInRoot]
phase = release

[Regenerate::AfterReleasers]
plugin = CopyFilesFromRelease
plugin = ReadmeGFMInRoot

;;; Release
[Libarchive]
[TestRelease]
[RunExtraTests]
[ConfirmRelease]
[UploadToCPAN]

[Git::Check]
[Git::Remote::Check]
branch = master
[@Git::VersionManager]
-remove = Prereqs
commit_files_after_release = Makefile.PL
commit_files_after_release = META.json
commit_files_after_release = LICENSE
commit_files_after_release = README.md
NextRelease.format = %-9v %{yyyy-MM-dd}d%{ (TRIAL RELEASE)}T
[Git::Push]
